version: "3.9"

services:
  django:
    container_name: django
    build:
      context: server/
    image: django
    healthcheck:
      test: python manage.py check || exit 1
      interval: 1m
      timeout: 20s
      retries: 2
      start_period: 10s
    restart: always
    volumes:
      - media_files:/media
      - statis_files:/static
      - logs_files:/logs
      - /root/school/server/db.sqlite3:/db.sqlite3
    networks:
      net:
        ipv4_address: 192.168.10.3

  nginx:
      container_name: nginx
      image: nginx:stable
      healthcheck:
        test: service nginx status || exit 1
        interval: 1m
        timeout: 20s
        retries: 2
        start_period: 5s
      depends_on:
        - django
      ports:
        - 80:80
        - 443:443
      expose:
        - 80
        - 443
      restart: always
      volumes:
        - /etc/letsencrypt/:/ssl/
        - /root/certbot/:/certbot/
        - ./web/nginx.conf:/etc/nginx/nginx.conf
        - media_files:/media
        - statis_files:/static
      networks:
        net:
          ipv4_address: 192.168.10.2

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/29
          gateway: 192.168.10.1

volumes:
  media_files:
  statis_files:
  logs_files:
  db:
